apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nlbp6t8bw-python
  janus-idp.io/tekton: nlbp6t8bw-python
  backstage.io/kubernetes-id: nlbp6t8bw-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: nlbp6t8bw-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
