apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: nlbp6t8bw-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nlbp6t8bw-python 
  name: nlbp6t8bw-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: nlbp6t8bw-python
    weight: 100 
